name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'  
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add Upstream and Sync
        run: |
          git remote add upstream https://github.com/rancoor/dash.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main --ff-only || git merge upstream/main --no-edit
          git push origin main
