name: Sync Fork with Upstream

on:
  schedule:
    - cron: '* * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config --global user.name "rancoor"
          git config --global user.email "cheruiyotca@gmail.com"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/rancoor/dash.git || true
          git fetch upstream

      - name: Merge Changes
        run: |
          git checkout main
          git merge --no-ff upstream/main --no-edit || git rebase upstream/main

      - name: Push to Fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
